version: "3.8"

services:
  rust-streamer:
    build: ./rust-streamer
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - market_net

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - market_net

  python-api:
    build: ./python-api
    depends_on:
      - redis
      - rust-streamer
    ports:
      - "8000:8000"
    networks:
      - market_net

networks:
  market_net:
    driver: bridge
