services:
  rust-streamer:
    build: ./rust-streamer
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - market_net

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - market_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  python-api:
    build: ./python-api
    depends_on:
      redis:
        condition: service_healthy
      rust-streamer:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - market_net

networks:
  market_net:
    driver: bridge
