[package]
name = "rust-streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.2"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
redis = "0.29.0"
